spring:
  flyway:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:register}?createDatabaseIfNotExist=true
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
    schemas:
      - ${DATABASE:register}
  application:
    name: register
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:register}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
    platform: Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 450
      minimum-idle: 50
      idle-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        jdbc:
          time_zone: UTC
          batch_size: ${JBDC_BATCH_SIZE:50}
      type: trace

kafka:
  bootstrapServers: 127.0.0.1:9092
  acksConfig: all
  retriesConfig: 10
  schemaRegistryUrl: "http://127.0.0.1:8081"